FROM golang:1.22-alpine3.20 AS builder

WORKDIR /tickets-booking

COPY go.mod go.sum ./

RUN go mod download

COPY . .

WORKDIR /tickets-booking/services/auth

RUN go build -o ./cmd/app/app ./cmd/app/main.go

FROM alpine:3.20

WORKDIR /tickets-booking

COPY --from=builder /tickets-booking /tickets-booking/