networks:
  dev:

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - dev

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_DB=auth_service_db
    networks:
      - dev

  auth:
    build:
      context: .
      dockerfile: ./services/auth/dockerfile
    command: ["/tickets-booking/services/auth/cmd/app/app"]
    ports:
      - 8080:8080
    networks:
      - dev
    depends_on:
      - redis
      - postgres

  gateway:
    build: 
      context: .
      dockerfile: ./services/gateway/dockerfile
    command: ["/tickets-booking/services/gateway/cmd/app/app"]
    ports:
      - 3000:3000
    networks:
      - dev
    depends_on:
      - auth