server:
  port: "8080"

database:
  user: "postgres"
  password: "mypass"
  db_name: "auth_service_db"
  ssl_mode: "disable"
  host: "postgres"
  port: "5432"

cache:
  host: "redis"
  port: "6379"
  password: "mypass"
